/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_chtlei_mydemo_jnitest_JNIUtils */

#ifndef _Included_com_example_chtlei_mydemo_jnitest_JNIUtils
#define _Included_com_example_chtlei_mydemo_jnitest_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_chtlei_mydemo_jnitest_JNIUtils
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_chtlei_mydemo_jnitest_JNIUtils_stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_example_chtlei_mydemo_jnitest_JNIUtils
 * Method:    encryptString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_chtlei_mydemo_jnitest_JNIUtils_encryptString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
